/**:
  ros__parameters:
    camera:
      i_calibration_dump: false
      i_enable_diagnostics: true
      i_enable_ir: true
      i_enable_sync: false
      i_nn_type: none
      i_pipeline_type: RGB
      i_rs_compat: false
    rgb:
      i_add_exposure_offset: false
      i_board_socket_id: 0
      i_calibration_file: ""
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_enable_preview: false
      i_exposure_offset: 0
      i_fps: 30.0
      i_low_bandwidth_frame_freq: 20
      i_low_bandwidth: true
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: h265
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 80
      i_fsync_continuous: false
      i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_interleaved: false
      i_keep_preview_aspect_ratio: true
      i_max_q_size: 30
      i_preview_height: 300
      i_preview_size: 300
      i_preview_width: 300
      i_publish_compressed: true
      i_publish_topic: true
      i_resolution: 4K
      i_height: 1440
      i_width: 2560
      i_reverse_stereo_socket_order: false
      i_sensor_img_orientation: AUTO
      i_output_isp: false
      i_isp_den: 3
      i_isp_num: 2
      i_set_isp3a_fps: false
      i_set_isp_scale: true
      i_simulate_from_topic: false
      i_simulated_topic_name: ""
      i_synced: false
      i_update_ros_base_time_on_ros_msg: false
      r_exposure: 3001
      r_focus: 126
      r_iso: 100
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_whitebalance: 6600